// @ts-check

/**
 * The lesson sidebar is generated automatically from the docs folder.
 * Ordering comes from each file's `sidebar_position` frontmatter, which the
 * migration script sets to the original curriculum order.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  dersSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
